name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 1. 루트 경로를 유지한 채, Shop 폴더 안의 gradlew를 실행해 빌드합니다.
    - name: Build with Gradle
      run: |
        chmod +x ./Shop/gradlew
        ./Shop/gradlew clean build -x test -p ./Shop

    # 2. 헷갈리지 않게 빌드된 파일의 절대적인 경로를 정확히 찝어서 Azure로 보냅니다.
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mymall-ebook'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'Shop/build/libs/*.jar'